name: 'Build Rootfs'
description: 'Build a distro rootfs'
inputs:
  distro:
    description: 'Distribution to build'
    required: true
  skip-archs:
    description: 'Architectures to skip'
    required: false
    default: "x86_64 i686 i386 riscv64"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget curl jq xz-utils \
          mmdebstrap \
          qemu-user-static \
          binfmt-support \
          git sudo tar \
          zstd

        # Install missing keyrings for mmdebstrap
        curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
        sudo apt install -yq /tmp/mmdebstrap.deb || true
        curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
        sudo apt install -yq /tmp/keyring.deb || true

        # Trisquel keyring
        curl -L -o /tmp/trisquelkey.deb https://archive.trisquel.org/trisquel/pool/main/t/trisquel-keyring/trisquel-keyring_2023.02.07_all.deb
        sudo apt install -yq /tmp/trisquelkey.deb || true

        # Register binfmt
        sudo update-binfmts --enable

    - name: Build
      shell: bash
      env:
        DISTRO: ${{ inputs.distro }}
        SKIP_ARCHS: ${{ inputs.skip-archs }}
        XZ_OPT: "-T0"
      run: |
        set -e
        # Export for the script
        export SKIP_ARCHS="$SKIP_ARCHS"

        if [ ! -f ./distro-build/${DISTRO}.sh ]; then
           echo "Error: Recipe for ${DISTRO} not found!"
           exit 1
        fi

        chmod +x bootstrap-rootfs.sh
        sudo -E ./bootstrap-rootfs.sh ${DISTRO}

    - name: Verify
      shell: bash
      run: |
        if [ -d "rootfs" ] && [ "$(ls -A rootfs/ 2>/dev/null)" ]; then
          echo "Build successful."
          ls -la rootfs/
        else
          echo "Build failed: No output files."
          exit 1
        fi
