name: 'Plan Build'
description: 'Determine which distributions to build based on changes'
inputs:
  event-name:
    description: 'Event name'
    required: true
  distributions:
    description: 'Distributions input (workflow_dispatch)'
    required: false
  pr-base-sha:
    description: 'PR base SHA'
    required: false
  pr-head-sha:
    description: 'PR head SHA'
    required: false
  before-sha:
    description: 'Push before SHA'
    required: false
  head-sha:
    description: 'Push head SHA'
    required: false
outputs:
  matrix:
    description: "JSON array of distributions to build"
    value: ${{ steps.plan.outputs.matrix }}
  should_build:
    description: "Whether to run the build job"
    value: ${{ steps.plan.outputs.should_build }}
runs:
  using: "composite"
  steps:
    - id: plan
      shell: bash
      env:
        EVENT_NAME: ${{ inputs.event-name }}
        INPUT_DISTROS: ${{ inputs.distributions }}
        PR_BASE: ${{ inputs.pr-base-sha }}
        PR_HEAD: ${{ inputs.pr-head-sha }}
        BEFORE_SHA: ${{ inputs.before-sha }}
        HEAD_SHA: ${{ inputs.head-sha }}
      run: |
        distros=""
        should_build="false"

        if [ "$EVENT_NAME" == "workflow_dispatch" ]; then
          distros="$INPUT_DISTROS"
          should_build="true"
        else
          # Determine the base commit for diff
          if [ "$EVENT_NAME" == "pull_request" ]; then
            base_sha="$PR_BASE"
            head_sha="$PR_HEAD"
          else
            base_sha="$BEFORE_SHA"
            head_sha="$HEAD_SHA"
          fi

          if [ -n "$base_sha" ]; then
            # Verify if base_sha exists in the local repository
            if ! git cat-file -e "$base_sha" 2>/dev/null; then
              echo "Base SHA $base_sha not found locally. Falling back to parent of HEAD."
              base_sha=$(git log -1 --pretty=%P HEAD | awk '{print $1}')
            fi
          fi

          if [ -z "$base_sha" ] || [ "$base_sha" == "0000000000000000000000000000000000000000" ]; then
              base_sha=$(git log -1 --pretty=%P HEAD | awk '{print $1}')
              [ -z "$base_sha" ] && base_sha=$(git hash-object -t tree /dev/null)
          fi

          echo "Diffing between $base_sha and $head_sha"
          git diff-tree --no-commit-id --name-only -r "$base_sha" "$head_sha" > ./files_changed.txt

          echo "Changed files:"
          cat ./files_changed.txt

          # Check for changes in core files or any action definition
          if grep -qE '^bootstrap-rootfs.sh$|^\.github/workflows/build-distro.yml$|^\.github/actions/.*' ./files_changed.txt; then
            echo "Core files changed. Building ALL distributions."
            distros=$(ls -1 distro-build/*.sh | sed 's@distro-build/\(.*\)\.sh@\1@' | tr '\n' ' ')
            should_build="true"
          elif grep -q '^distro-build/.*\.sh$' ./files_changed.txt; then
            echo "Specific distributions changed."
            distros=$(grep '^distro-build/.*\.sh$' ./files_changed.txt | sed 's@distro-build/\(.*\)\.sh@\1@' | tr '\n' ' ')
            should_build="true"
          else
            echo "No relevant changes found."
          fi
        fi

        echo "should_build=$should_build" >> $GITHUB_OUTPUT

        # Clean up formatting for JSON array
        # 1. Replace newlines with spaces (already done partially above)
        # 2. Trim leading/trailing spaces
        # 3. Convert space-separated string to JSON array

        # Ensure inputs are clean space-separated
        clean_distros=$(echo "$distros" | xargs)

        if [ -n "$clean_distros" ]; then
          # Generate JSON array: ["distro1", "distro2"]
          # jq -R -c 'split(" ") | map(select(length > 0))' reads the input string, splits by space, filters empties
          json_array=$(echo "$clean_distros" | tr -d '\n' | jq -R -c 'split(" ") | map(select(length > 0))')
          echo "Matrix JSON: $json_array"
          echo "matrix=$json_array" >> $GITHUB_OUTPUT
        else
          echo "matrix=[]" >> $GITHUB_OUTPUT
        fi
